package com.securechat.core.security

import android.util.Base64
import java.security.*
import java.security.spec.ECGenParameterSpec
import java.security.spec.X509EncodedKeySpec
import javax.crypto.KeyAgreement
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * Implements the **X3DH (Extended Triple Diffie-Hellman)** key agreement used
 * in the Signal Protocol to establish a shared master secret between two parties
 * without requiring both to be online simultaneously.
 *
 * Key roles:
 * - **Identity Key (IK)**: Long-lived signing/agreement key, represents the user.
 * - **Signed PreKey (SPK)**: Medium-lived key uploaded to the server, rotated weekly.
 * - **One-Time PreKeys (OPK)**: Ephemeral keys consumed on first contact.
 * - **Ephemeral Key (EK)**: Generated by the *initiator* for each new session.
 *
 * Both keys use ECDH on Curve P-256 (X9.62 prime256v1), supported natively on
 * all Android devices via `java.security`.
 */
class X3DHKeyManager(private val keystoreManager: KeystoreManager) {

    companion object {
        private const val EC_CURVE       = "prime256v1"  // aka secp256r1 / P-256
        private const val KEY_ALGO       = "EC"
        private const val AGREEMENT_ALGO = "ECDH"
        private const val HMAC_ALGO      = "HmacSHA256"
        /** Number of one-time prekeys to generate in a batch upload. */
        const val ONE_TIME_PREKEY_COUNT  = 100
    }

    // ── Key Generation ────────────────────────────────────────────────────────

    /** Generates a fresh EC key pair on P-256. */
    fun generateKeyPair(): KeyPair {
        val generator = KeyPairGenerator.getInstance(KEY_ALGO)
        generator.initialize(ECGenParameterSpec(EC_CURVE), SecureRandom())
        return generator.generateKeyPair()
    }

    /**
     * Generates the full set of keys required for registration:
     *  - Identity key pair (IK)
     *  - Signed PreKey pair (SPK)
     *  - [ONE_TIME_PREKEY_COUNT] one-time PreKey pairs (OPK)
     *
     * The private keys are wrapped and stored inside the Android Keystore via
     * [KeystoreManager]. Only public keys are returned for server upload.
     */
    fun generateRegistrationBundle(): RegistrationBundle {
        val identityKeyPair  = generateKeyPair()
        val signedPreKeyPair = generateKeyPair()
        val oneTimePreKeys   = (1..ONE_TIME_PREKEY_COUNT).map { generateKeyPair() }

        // Sign the SPK with the identity key so the server can verify authenticity.
        val spkSignature = signPublicKey(identityKeyPair.private, signedPreKeyPair.public)

        return RegistrationBundle(
            identityPublicKey  = encodePublicKey(identityKeyPair.public),
            signedPrePublicKey = encodePublicKey(signedPreKeyPair.public),
            spkSignature       = Base64.encodeToString(spkSignature, Base64.NO_WRAP),
            oneTimePrePublicKeys = oneTimePreKeys.mapIndexed { idx, kp ->
                PreKeyBundle(id = idx, publicKey = encodePublicKey(kp.public))
            },
            // Private keys are wrapped for local storage (never sent to server).
            wrappedIdentityPrivate  = keystoreManager.wrapSessionKey(identityKeyPair.private.encoded),
            wrappedSignedPrePrivate = keystoreManager.wrapSessionKey(signedPreKeyPair.private.encoded),
            wrappedOneTimePrivates  = oneTimePreKeys.map {
                keystoreManager.wrapSessionKey(it.private.encoded)
            },
        )
    }

    // ── X3DH Session Establishment ────────────────────────────────────────────

    /**
     * **Initiator side** (Alice sending first message to Bob):
     *
     * Performs X3DH with Bob's public PreKey bundle to derive a shared master secret.
     * Returns the [X3DHResult] containing the shared secret and the ephemeral public
     * key that must be sent to Bob so he can reproduce the secret.
     *
     * DH = ECDH(IK_A, SPK_B) || ECDH(EK_A, IK_B) || ECDH(EK_A, SPK_B)
     *    + ECDH(EK_A, OPK_B) if a one-time prekey is available.
     */
    fun initiatorX3DH(
        aliceIdentityPrivate: PrivateKey,
        aliceIdentityPublic: PublicKey,
        bobIdentityPublic: PublicKey,
        bobSignedPrePublic: PublicKey,
        bobOneTimePrePublic: PublicKey?,
    ): X3DHResult {
        val ephemeralKeyPair = generateKeyPair()

        val dh1 = ecdh(aliceIdentityPrivate, bobSignedPrePublic) // DH1
        val dh2 = ecdh(ephemeralKeyPair.private, bobIdentityPublic) // DH2
        val dh3 = ecdh(ephemeralKeyPair.private, bobSignedPrePublic) // DH3
        val dh4 = bobOneTimePrePublic?.let { ecdh(ephemeralKeyPair.private, it) } // DH4 (optional)

        val master = hkdf(
            input = dh1 + dh2 + dh3 + (dh4 ?: ByteArray(0)),
            salt  = ByteArray(32), // zeros
            info  = "SecureChat X3DH".toByteArray(),
            length = 32,
        )

        return X3DHResult(
            masterSecret    = master,
            ephemeralPublic = encodePublicKey(ephemeralKeyPair.public),
        )
    }

    /**
     * **Responder side** (Bob receiving Alice's initial message):
     *
     * Reconstructs the shared master secret using Alice's ephemeral public key
     * and Bob's local private keys.
     */
    fun responderX3DH(
        bobIdentityPrivate: PrivateKey,
        bobSignedPrePrivate: PrivateKey,
        bobOneTimePrePrivate: PrivateKey?,
        aliceIdentityPublic: PublicKey,
        aliceEphemeralPublic: PublicKey,
    ): ByteArray {
        val dh1 = ecdh(bobSignedPrePrivate, aliceIdentityPublic)
        val dh2 = ecdh(bobIdentityPrivate, aliceEphemeralPublic)
        val dh3 = ecdh(bobSignedPrePrivate, aliceEphemeralPublic)
        val dh4 = bobOneTimePrePrivate?.let { ecdh(it, aliceEphemeralPublic) }

        return hkdf(
            input  = dh1 + dh2 + dh3 + (dh4 ?: ByteArray(0)),
            salt   = ByteArray(32),
            info   = "SecureChat X3DH".toByteArray(),
            length = 32,
        )
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    /** Performs a raw ECDH key agreement step. */
    fun ecdh(privateKey: PrivateKey, publicKey: PublicKey): ByteArray {
        val ka = KeyAgreement.getInstance(AGREEMENT_ALGO)
        ka.init(privateKey)
        ka.doPhase(publicKey, true)
        return ka.generateSecret()
    }

    /** Derives [length] bytes from [input] using HKDF-SHA256. */
    fun hkdf(input: ByteArray, salt: ByteArray, info: ByteArray, length: Int): ByteArray {
        // Extract
        val prk = hmacSha256(salt, input)
        // Expand
        val result = ByteArray(length)
        var prev = ByteArray(0)
        var pos = 0
        var counter = 1
        while (pos < length) {
            prev = hmacSha256(prk, prev + info + byteArrayOf(counter.toByte()))
            val toCopy = minOf(prev.size, length - pos)
            prev.copyInto(result, pos, 0, toCopy)
            pos += toCopy
            counter++
        }
        return result
    }

    private fun hmacSha256(key: ByteArray, data: ByteArray): ByteArray {
        val mac = Mac.getInstance(HMAC_ALGO)
        mac.init(SecretKeySpec(key, HMAC_ALGO))
        return mac.doFinal(data)
    }

    /** Signs [publicKeyToSign] with [signingPrivateKey] using SHA256withECDSA. */
    private fun signPublicKey(signingPrivateKey: PrivateKey, publicKeyToSign: PublicKey): ByteArray {
        val sig = Signature.getInstance("SHA256withECDSA")
        sig.initSign(signingPrivateKey)
        sig.update(publicKeyToSign.encoded)
        return sig.sign()
    }

    /** Encodes a PublicKey to Base64 (X.509 SubjectPublicKeyInfo format). */
    fun encodePublicKey(key: PublicKey): String =
        Base64.encodeToString(key.encoded, Base64.NO_WRAP)

    /** Decodes a Base64-encoded public key back to a [PublicKey]. */
    fun decodePublicKey(encoded: String): PublicKey {
        val bytes = Base64.decode(encoded, Base64.NO_WRAP)
        val spec = X509EncodedKeySpec(bytes)
        return KeyFactory.getInstance(KEY_ALGO).generatePublic(spec)
    }
}

// ── Data Transfer Objects ─────────────────────────────────────────────────────

/** Keys uploaded to the server during registration. */
data class RegistrationBundle(
    val identityPublicKey: String,
    val signedPrePublicKey: String,
    val spkSignature: String,
    val oneTimePrePublicKeys: List<PreKeyBundle>,
    // Private halves — stored locally, never sent.
    val wrappedIdentityPrivate: EncryptedPayload,
    val wrappedSignedPrePrivate: EncryptedPayload,
    val wrappedOneTimePrivates: List<EncryptedPayload>,
)

data class PreKeyBundle(
    val id: Int,
    val publicKey: String,
)

data class X3DHResult(
    val masterSecret: ByteArray,
    val ephemeralPublic: String,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is X3DHResult) return false
        return masterSecret.contentEquals(other.masterSecret) && ephemeralPublic == other.ephemeralPublic
    }
    override fun hashCode(): Int = 31 * masterSecret.contentHashCode() + ephemeralPublic.hashCode()
}
